// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sla.Api.Data;

#nullable disable

namespace Sla.Api.Migrations
{
    [DbContext(typeof(SlaDbContext))]
    [Migration("20261010043401_AddSlaTierPolicies")]
    partial class AddSlaTierPolicies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Sla.Api.Model.SlaTierPolicy", b =>
                {
                    b.Property<string>("TierName")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByAdminId")
                        .HasColumnType("longtext");

                    b.HasKey("TierName");

                    b.ToTable("SlaTierPolicies");

                    b.HasData(
                        new
                        {
                            TierName = "LOW",
                            DurationMinutes = 2880,
                            LastUpdatedAtUtc = new DateTime(2026, 10, 10, 4, 34, 1, 321, DateTimeKind.Utc).AddTicks(3945)
                        },
                        new
                        {
                            TierName = "MEDIUM",
                            DurationMinutes = 1440,
                            LastUpdatedAtUtc = new DateTime(2026, 10, 10, 4, 34, 1, 321, DateTimeKind.Utc).AddTicks(3947)
                        },
                        new
                        {
                            TierName = "HIGH",
                            DurationMinutes = 240,
                            LastUpdatedAtUtc = new DateTime(2026, 10, 10, 4, 34, 1, 321, DateTimeKind.Utc).AddTicks(3948)
                        },
                        new
                        {
                            TierName = "CRITICAL",
                            DurationMinutes = 60,
                            LastUpdatedAtUtc = new DateTime(2026, 10, 10, 4, 34, 1, 321, DateTimeKind.Utc).AddTicks(3950)
                        });
                });

            modelBuilder.Entity("Sla.Api.Model.TicketSla", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("TargetResolutionTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TicketId");

                    b.ToTable("TicketSlas");
                });
#pragma warning restore 612, 618
        }
    }
}
